### ISSUE TITLE
Docker should mount (not clone) sequencer repo

### ISSUE THREAD

**Issue by mekarpeles** [Open-Book-Genome-Project/sequencer#83]
See Problem:
> the container made by the dockerfile contains the cloned git repo of sequencer as while building the image it performs a fresh git clone. So while developing we cannot use the docker because the local changes will not be reflected.
https://github.com/Open-Book-Genome-Project/sequencer/pull/82#issuecomment-1027698762

See Solution:
https://github.com/Open-Book-Genome-Project/sequencer/pull/82#issuecomment-1028582087
I believe the solution is to remove https://github.com/Open-Book-Genome-Project/sequencer/blob/master/Dockerfile#L3 and then within volumes add https://github.com/Open-Book-Genome-Project/sequencer/blob/master/docker-compose.yml#L6

```
volumes:
    - ./:/sequencer
```

**Comment by mekarpeles** [comment]
@hitansh would you like to try this one?

**Comment by Hitansh-Shah** [comment]
@mekarpeles Sure.

**Comment by Hitansh-Shah** [comment]
I took a day off yesterday 😅. I will open PR for this today itself.
