### ISSUE TITLE
OBGP Sequencer 2-grams recognizing spaces as words

### ISSUE THREAD

**Issue by Teo-J-Cheng** [Open-Book-Genome-Project/sequencer#86]
The OBGP Sequencer 2-grams module seems to have a problem where it identifies a space as a word. This might be because there are two spaces next to each other which triggers a bug in the code.

**Comment by mekarpeles** [comment]
Here is an example of a book that is breaking
https://archive.org/download/isbn_1842738577/book_genome.json

Here's a list of the first few 2grams (many of which seem wrong)
```
2grams: [
[
" ",
2264
],
[
" es",
319
],
[
" ee",
186
],
[
" 3",
171
],
[
" e",
169
],
[
"3 ",
126
],
[
"es ",
122
],
[
"es ee",
109
],
[
"e ",
97
],
[
" s",
97
],
```

**Comment by Billa05** [comment]
hey @mekarpeles, After exploring the project and testing the issue, I found that the issue no longer exists. I ran the script and the output was satisfactory. Please find the output [here](https://github.com/Billa05/sequencer/tree/master/testing)

**Comment by mekarpeles** [comment]
Thank you @Billa05 !
